name: Vite Github Pages Deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master", "main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js '16.x'
      uses: actions/setup-node@v2
      with:
        node-version: "16.x"
        cache: "npm"
    - id: Build-Vue
      uses: SerhiiKa/VuePagesAction@1.0.4
      with:
        username: 'ROAServer'
        reponame: 'ROAServerWebsite'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
