name: Build to Release when push version Tag

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: github-pages
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4.1.0
        with:
          node-version: 20
      - run: npm install

      - name: build
        run: npm run build

      - name: zip files
        run: zip -r release.zip ./dist/

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: release.zip
